### ISSUE TITLE
Feature request: Disable z-scroll on 2d images

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#1]
Hi! I've been trying the webilastik demo available through ebrains as I am one of the developers working with the QUINT workflow tools. WebIlastik works well and is very cool! I was wondering if it would be possible to disable z scroll when a user is editing a 2d image, as well as preventing pitch and yaw changes which can occur if you press shift + drag. Just some things I thought could be useful, not urgent.

**Comment by Tomaz-Vieira** [comment]
Hello!

You are absolutely right; this is some very annoying behavior from webilastik.

The reasoning behind it is that webilastik was built with the intention of being used as a plugin/overlay on top of different viewers, and not as a standalone application. Because of that, webilastik is very conservative on what it will do the viewer as not to mess too much with the environment into which it has been injected. The compromise for now is that "recenter" button in case you go past the single layer of your 2D data, but I understand that it's far from ideal.

The need for webilastik to be an overlay is still under discussion, and it's possible that this requirement will be dropped soon, in which case I can be a bit more aggressive with the underlying viewer and fix this issue properly =)

**Comment by PolarBean** [comment]
interesting to know! So others will build the viewers that Ilastik plugs into? thanks for the information

**Comment by Tomaz-Vieira** [comment]
I've actually implemented this now =)
There might still be some corner-cases where it might fail but overall it seems ok

**Comment by PolarBean** [comment]
I just did a quick test on the demo images [here](https://app.ilastik.org/public/nehuba/index.html#!%7B%22layers%22:%5B%7B%22source%22:%22precomputed://https://app.ilastik.org/public/images/mouse1.precomputed%22%2C%22type%22:%22image%22%2C%22blend%22:%22default%22%2C%22shader%22:%22void%20main%28%29%20%7B%5Cn%20%20%20%20vec3%20color0%20=%20%28vec3%28255%2C%200%2C%200%29%20/%20255.0%29%20%2A%20toNormalized%28getDataValue%280%29%29%3B%5Cn%20%20%20%20vec3%20color1%20=%20%28vec3%280%2C%20255%2C%200%29%20/%20255.0%29%20%2A%20toNormalized%28getDataValue%281%29%29%3B%5Cn%20%20%20%20vec3%20color2%20=%20%28vec3%280%2C%200%2C%20255%29%20/%20255.0%29%20%2A%20toNormalized%28getDataValue%282%29%29%3B%5Cn%20%20%20%20emitRGBA%28%5Cn%20%20%20%20%20%20%20%20vec4%28color0%20+%20color1%20+%20color2%2C%201.0%29%5Cn%20%20%20%20%29%3B%5Cn%7D%22%2C%22name%22:%22mouse1.precomputed%22%7D%5D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B1%2C1%2C1%5D%2C%22voxelCoordinates%22:%5B2062%2C1245.5%2C0.5%5D%7D%7D%2C%22zoomFactor%22:1%7D%2C%22layout%22:%22xy%22%7D) and the scroll wheel still adjusts the z-plane. are the changes live yet, or perhaps it is something specific to the demo images.

**Comment by Tomaz-Vieira** [comment]
Hey, sorry about that. I had added the Z-scrolling logic to after a compute session was allocated. I've fixed it now and it should work even before you have a session running.

**Comment by PolarBean** [comment]
Makes sense, it is working beautifully now
