### ISSUE TITLE
Hotkey to enable brushing

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#11]
This is likely a matter of personal preference but it might be useful to have a hotkey to enable brushing. For instance while in navigation mode holding a particular key might switch to brushing mode, while releasing might switch back to navigation. Alternatively you could use a key as a toggle. Keen to hear your perspective. :)

**Comment by Tomaz-Vieira** [comment]
I agree. At least it should be possible to draw the brush strokes and navigate without having to click the brushing checkbox back and forth. This is also one of those legacy consequences of ilastik being at first envisioned as a plugin rather than a standalone app.

There are some technical issues to overcome to make it possible, but I should be able to make it at least less painful.

**Comment by Tomaz-Vieira** [comment]
Done. It's `B`, for "Brushing" =)

**Comment by PolarBean** [comment]
Nice! thank you
